name: My Slark Text Workflow
#test

#trigger
on:
   push:
     branches:
        - 'release/v[0-9]+.[0-9]*'

jobs:
    #name of your job
    my-first-job:
        #runner
        runs-on: ubuntu-latest    

        #steps in this job
        steps:
          - name: checkout source code
            uses: actions/checkout@v4

          - name: Run Trivy vulnerability scanner in fs mode
            uses: aquasecurity/trivy-action@master
            with:
                scan-type: 'fs'
                scan-ref: '.'
                severity: 'HIGH'


          - name: Notify on failure
            if: steps.trivy-scan.outcome == 'failure'
            run: |
                  echo "Failed Trivy scan."

          - name: Notify on success
            if: steps.trivy-scan.outcome == 'success'
            run: |
                  echo "Success."



          - name: Send GitHub Action trigger data to Slack workflow
            id: slack
            uses: slackapi/slack-github-action@v1.26.0
            with:
                 payload: |
                  { 
                    "text": "Actions URL:${{github.action}}", 
      
                    "blocks": [
                        {
                          "type": "section",
                          "fields": [
                            {
                              "type": "mrkdwn",
                              "text": "*Name:* person name\n*Metriculation:* person number\n*Email:* person email\n*Git:* ${{github.server_url}}/${{github.repository}}\n*Image:* Image URL"

                            }]
                         }
                    ]
                  }
            env:
                SLACK_WEBHOOK_URL: ${{ secrets.P_SLACK_API }}
                SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
