name: Build and Push

#trigger
on:
   push:
     branches:
        - 'release/v[0-9]+.[0-9]*'

jobs:
    #name of your job
    fs-scan:
        #runner
        runs-on: ubuntu-latest    
        if: "!startsWith(github.event.head_commit.message, '#NORUN')"
        #steps in this job
        steps:
          - name: checkout source code
            uses: actions/checkout@v4


            #Trivy fs -s file(.)
          - name: Run Trivy vulnerability scanner in fs mode
            uses: aquasecurity/trivy-action@master
            with:
                scan-type: 'fs'
                scan-ref: '.'
                format: 'json'
                output: 'trivy-report.json'
                github-pat: ${{ secrets.MY_API }} # or ${{ secrets.github_pat_name }} if you're using a PAT
                severity: 'CRITICAL' #CRITICAL



          
            #consign generate key pairs
            #consign sign--key consign.key <account>/myapp:<git-commit>
          - name: Generate Cosign Key Pairs
            id: generate_keys
            run: |
             mkdir -p keys
             cd keys
             cosign generate-key-pair


            ## Error is file path directionary
          # - name: Sign Docker Image
          #   run: |
          #       cosign sign --key cosign.key ${{ github.repository }}:${{ github.event.head_commit.message }}
      

     
    


           #Slack notification (Currently, fomart is wrong)
          - name: Set Slack message
            id: set-slack-message
            run: |
                SLACK_TITLE="Image build and signed"
                SLACK_MESSAGE="*Name:* person name\n*Metriculation:* person number\n*Email:* person email\n*Git:* ${{ github.server_url }}/${{ github.repository }}\n*Image:* Image URL"

          - name: Slack Notification
            uses: rtCamp/action-slack-notify@v2
            env:
                SLACK_WEBHOOK: ${{ secrets.P_SLACK_API }}
                SLACK_MESSAGE: ${{ steps.set-slack-message.outputs.message }}


          - name: Send GitHub Action trigger data to Slack workflow
            id: slack
            uses: slackapi/slack-github-action@v1.26.0
            with:
                payload: |
                 { 
                    "blocks": [
                    {
                        "type": "section",
                        "fields": [
                        {
                            "type": "mrkdwn",
                            "text": "*Name:* person name\n*Metriculation:* person number\n*Email:* person email\n*Git:* ${{github.server_url}}/${{github.repository}}\n*Image:* <https://hub.docker.com/repository/docker/${{ github.repository }}>"

                        }]
                        }
                    ]
                 }
            env:
                 SLACK_WEBHOOK_URL: ${{ secrets.P_SLACK_API }}
                 SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
